// For description of these values see http://adblockplus.org/en/preferences

pref("extensions.libertyblocker.currentVersion", "0.0");
pref("extensions.libertyblocker.enabled", true);
pref("extensions.libertyblocker.frameobjects", true);
pref("extensions.libertyblocker.fastcollapse", false);
pref("extensions.libertyblocker.showinstatusbar", false);
pref("extensions.libertyblocker.detachsidebar", false);
pref("extensions.libertyblocker.defaulttoolbaraction", 0);
pref("extensions.libertyblocker.defaultstatusbaraction", 0);
pref("extensions.libertyblocker.sidebar_key", "Accel Shift V, Accel Shift U");
pref("extensions.libertyblocker.sendReport_key", "");
pref("extensions.libertyblocker.filters_key", "Accel Shift E, Accel Shift F, Accel Shift O");
pref("extensions.libertyblocker.enable_key", "");
pref("extensions.libertyblocker.flash_scrolltoitem", true);
pref("extensions.libertyblocker.previewimages", true);
pref("extensions.libertyblocker.data_directory", "libertyblocker");
pref("extensions.libertyblocker.patternsbackups", 5);
pref("extensions.libertyblocker.patternsbackupinterval", 24);
pref("extensions.libertyblocker.whitelistschemes", "about chrome file irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
pref("extensions.libertyblocker.subscriptions_autoupdate", true);
pref("extensions.libertyblocker.subscriptions_listurl", "https://adblockplus.org/subscriptions2.xml");
pref("extensions.libertyblocker.subscriptions_fallbackurl", "https://adblockplus.org/getSubscription?version=%VERSION%&url=%SUBSCRIPTION%&downloadURL=%URL%&error=%ERROR%&channelStatus=%CHANNELSTATUS%&responseStatus=%RESPONSESTATUS%");
pref("extensions.libertyblocker.subscriptions_fallbackerrors", 5);
pref("extensions.libertyblocker.subscriptions_exceptionsurl", "https://easylist-downloads.adblockplus.org/exceptionrules.txt");
pref("extensions.libertyblocker.subscriptions_exceptionscheckbox", true);
pref("extensions.libertyblocker.documentation_link", "https://adblockplus.org/redirect?link=%LINK%&lang=%LANG%");
pref("extensions.libertyblocker.savestats", true);
pref("extensions.libertyblocker.composer_default", 2);
pref("extensions.libertyblocker.clearStatsOnHistoryPurge", true);
pref("extensions.libertyblocker.report_submiturl", "https://reports.adblockplus.org/submitReport?version=1&guid=%GUID%&lang=%LANG%");
pref("extensions.libertyblocker.recentReports", []);
pref("extensions.libertyblocker.hideContributeButton", false);
pref("extensions.libertyblocker.blockableItemsSize", {width: 200, height: 200});
pref("extensions.libertyblocker.notificationurl", "https://notification.adblockplus.org/notification.json");
pref("extensions.libertyblocker.notificationdata", {});
pref("extensions.libertyblocker.subscriptions_antiadblockurl", "https://easylist-downloads.adblockplus.org/antiadblockfilters.txt");
